### ISSUE TITLE
Difference between mercat and mercat2?

### ISSUE THREAD

**Issue by wchow** [raw-lab/mercat2#1]
Hi

I was wondering what the main difference between mercat and mercat2 is.  From the readme, it looks like the difference is the output, and the plots?  Is that correct or are there any differences in the underlying methods.

thanks!

**Comment by raw-lab** [comment]
Thank you for using Mercat. Mercat2 is update from Mercat1 - which includes use on python3+, PCA plots, output plots,  it handles large files, and higher throughput. The merging for higher throughput of many or large files is more streamlined but the results are the same. 
Please use mercat2 over mercat1. 

Let us know if you have any other questions?

many thanks!

**Comment by raw937** [comment]
Let us know if you have any other questions, bugs, or issues/problems? 
Also, if you need a specific or custom code in beta let us know?

many thanks!
