### ISSUE TITLE
Lack of diversity report after the completion of the run

### ISSUE THREAD

**Issue by Himmeshwar** [raw-lab/mercat2#11]
Hey,

I wanted to view some diversity metrics for my dataset but unfortunately, no file was generated containing the diversity metrics of the dataset. The program outputted a protein summary.txt file which contained numbers but with no description what the numbers meant and the html report wanted me download a .tsv file but I have not been able to successfully download the file. Any suggestion or help or clarification is welcome.

Thanks

**Comment by raw-lab** [comment]
Thank you for using MerCat2. 

Can you provide us with some further details?
From your command line type: lsb_release -a
Provide the command you used for MerCat2. 
Provide details of the dataset (for example): Illumina, 100 bp paired end, etc
Any errors from the terminal or .err log. 

MerCat2 provides tsv output that has kmer ID and kmer number. Also, well has html outputs on general statistics. 
Your also welcome to attach a small amount of your file for us to test. 

We will get you fixed up right away. Thank you for your patience. 

many thanks,
RAW Lab

**Comment by raw-lab** [comment]
Closing for now. The diversity stats are within our outputs. 

Thank you for using MerCat2

Many thanks,
RAW LAB
