### ISSUE TITLE
Recommendations

### ISSUE THREAD

**Issue by wchow** [raw-lab/mercat2#2]
Hi @raw-lab @raw937 

Thanks for your previous answer regarding the difference between mercat and mercat2.  I was wondering if you have any recommendations on:

1. Number of input reads to use (I have illumina reads and I've tried downsample 100k, 1M, 5M...etc)
2. kmer length (I've used k=21, which depending on input can impact speed of running)
3. I was thinking of using mercat2 to quickly calculate the shannon/simpsons index as a way to compare diversity between samples (running mercat individually on each sample).  I was wondering if that can be used that way, as a way to compare between samples.

thanks again for your help!

Will

**Comment by raw-lab** [comment]
Hello Will, 

We have removed the diversity estimation in mercat2 currently. We are working to improve the indexing so we can get a better species count with unique kmers. 

If you run mercat2 you can compare and run many samples at once an build a global comparison. Also, this will plot a PCA for you at the end. You can use all your reads this way. You don't have to downsample. Let us know if you lacking in cpu power we can help. 

What question are you asking? 
If it's just differences between samples?

**Comment by raw-lab** [comment]
If you run in protein mode it's much faster.

**Comment by wchow** [comment]
Thanks @raw-lab, 

I just want to see if I can estimate diversity on reads between samples before actually trying to assemble them.  Practically I want some relative metric so I can have a heads up before running more downstream analysis, and also how much compute I need to allocate.

thanks again for your help.

**Comment by raw-lab** [comment]
We have the new version MerCat2 if you would like.
