### ISSUE TITLE
How to find out the k-mers summary of protein fasta

### ISSUE THREAD

**Issue by LiangJzzz** [raw-lab/mercat2#6]
Hello! Mercat2 is a useful software to find out k-mers and I'm thankful for its help. I have a question that how to find out the k-mers summary of protein fasta after running Mercat2 using faa file. I just found a tsv file with a column title named 'count' and I couldn't understand the meaning of it. Hope your answer!

**Comment by raw-lab** [comment]
The count file provides you a list of kmers from the protein fasta with counts.

**Comment by raw937** [comment]
Should look something like this:
MTLL 101
MLLT 10

If it was a 4-mer you picked. Let us know?

**Comment by raw-lab** [comment]
Thank you for using MerCat2. We have a new update you should try. Let us know if any further issue arises? For now we are going to close this issue. 

many thanks,
RAW Lab
