### ISSUE TITLE
Option for transposed table output

### ISSUE THREAD

**Issue by pommevilla** [raw-lab/mercat2#7]
Thank you very much for this package, it's been a great help! 

It would be very helpful to have an option to output transposed tables, with the kmers along the columns and the fasta files as rows. I'm currently using an awk script to transpose them, but when `k` and the number of genomes get larger, memory becomes an issue.

**Comment by decrevi** [comment]
Thank you for your feedback!

Currently MerCat2 v1.3 outputs a combined transposed table in the main output folder (ends in "_T.tsv") assuming you give it at least 4 fasta files and run the PCA option with -pca. It should use less RAM than awk.

Is this what you are looking for?

**Comment by pommevilla** [comment]
Just ran it again and this is exactly what I was looking for. I'll go ahead and close this. Thank you!
